### ISSUE TITLE
Data not updated

### ISSUE THREAD

**Issue by saiffyros** [pocesar/apify-covid19-brazil#1]
It seems Brazilian govern changed their website because the data is not being updated. Deaths should be 18, but it shows only 4.
I'm talking about this btw: https://api.apify.com/v2/key-value-stores/TyToNta7jGKkpszMZ/records/LATEST?disableRedirect=true

**Comment by pocesar** [comment]
hello, yes, the Brazilian government went full rogue mode and decided to take down their only official channel with the cases, that were already lag behind compared to the reality and only updated every 24h: http://plataforma.saude.gov.br/novocoronavirus/

the data now needs to be extracted from news sources, like https://www.worldometers.info/coronavirus/country/brazil/ does

**Comment by pocesar** [comment]
@saiffyros it's fixed in 4b5a86d

it tries to parse the news from https://www.saude.gov.br/noticias/agencia-saude now. let's hope that they will keep doing this and providing that table
